param(
  [string]$Suite = "all",
  [string]$DevUrl = "http://localhost:5173",
  [switch]$NoDevServer,
  [string]$Model = "",
  [string]$ReportDir = "qa-reports"
)

$ErrorActionPreference = "Continue"

$suites = @{
  "analysis-hub"   = "qa_prompts\verify-analysis-hub.md"
  "cv-builder"     = "qa_prompts\verify-cv-builder.md"
  "cl-builder"     = "qa_prompts\verify-cl-builder.md"
  "profile"        = "qa_prompts\verify-profile.md"
  "config"         = "qa_prompts\verify-config.md"
  "ext-overlay"    = "qa_prompts\verify-extension-overlay.md"
  "onboarding"     = "qa_prompts\verify-onboarding.md"
}

$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$reportFile = "$ReportDir\qa-report-$timestamp.md"
New-Item -ItemType Directory -Path $ReportDir -Force | Out-Null

function Cleanup {
  Write-Host "Shutting down..." -ForegroundColor Yellow
  if ($devJob -and $devJob.State -eq "Running") { $devJob | Stop-Job -PassThru | Remove-Job }
}

trap { Cleanup; throw $_ }

if (-not $NoDevServer) {
  Write-Host "Starting Vite dev server..." -ForegroundColor Cyan
  $devJob = Start-Job -ScriptBlock { npm run dev }
  Start-Sleep -Seconds 4
}

Write-Host "Playwright MCP will be started by opencode (configured in opencode.json)" -ForegroundColor Cyan

$targetSuites = if ($Suite -eq "all") { $suites.Keys } else { @($Suite) }

$allResults = @()

foreach ($s in $targetSuites) {
  $promptFile = $suites[$s]
  if (-not (Test-Path $promptFile)) {
    Write-Warning "Suite '$s' not found at $promptFile"
    continue
  }

  Write-Host "Running QA suite: $s" -ForegroundColor Magenta

  $opencodeArgs = @("run", "QA verify $s", "--agent", "qa", "--file", $promptFile)
  if ($Model) { $opencodeArgs += "--model"; $opencodeArgs += $Model }
  $raw = & opencode @opencodeArgs 2>&1
  $clean = ($raw | ForEach-Object { "$_" }) -join "`n"
  $clean = $clean -replace '\e\[[0-9;]*[a-zA-Z]', ''
  $clean = $clean -replace '(?m)^opencode\.exe\s*:.*$', ''
  $clean = $clean -replace '(?m)^At C:\\Users\\.*opencode\.ps1:\d+ char:\d+$', ''
  $clean = $clean -replace '(?m)^\+.*$', ''
  $clean = $clean -replace '(?m)^\s{4}\+ CategoryInfo.*$', ''
  $clean = $clean -replace '(?m)^\s{4}\+ FullyQualifiedErrorId.*$', ''
  $clean = ($clean -split "`n" | Where-Object { $_.Trim() -ne '' }) -join "`n"
  $allResults += @{
    suite = $s
    timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    output = $clean
  }

  Write-Host "Suite '$s' complete. Output saved." -ForegroundColor Green
}

$report = @"
# QA Report — $timestamp

**Agent:** qa $(if ($Model) { "(model: $Model)" })
**Dev URL:** $DevUrl
**Suites:** $($targetSuites -join ', ')

$(foreach ($r in $allResults) {
@"

---

## Suite: $($r.suite)
**Run at:** $($r.timestamp)

```
$($r.output)
```

"@
})

---

*Generated by Artemis Quiver QA Runner*
"@

Set-Content -Path $reportFile -Value $report
Write-Host "QA report saved to: $reportFile" -ForegroundColor Green

Cleanup
